fastlane_version "2.47.0"
default_platform :ios

# Variables
scheme = "UXCamExample"
workspace = "#{scheme}.xcworkspace"

platform :ios do
  desc "Builds the app"
  lane :build do
    gym(
      workspace: workspace,
      scheme: scheme,
      clean: true,
      silent: true,
      suppress_xcode_output: true,
      export_method: "ad-hoc",
    )
  end
end
