source "https://github.com/CocoaPods/Specs.git"
platform :ios, "8.0"

target "UXCamExample" do
  pod "Yoga", path: "../node_modules/react-native/ReactCommon/yoga"
  pod "React", path: "../node_modules/react-native", subspecs: ["BatchedBridge", "Core"]
  pod "react-native-ux-cam", path: "../node_modules/react-native-ux-cam"
end
